import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const vazirFont = localFont({
  src: "../fonts/Vazir-Medium-FD.woff2",
  variable: "--font-Vazir-Medium-FD",
  weight: "400 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazirFont.variable} antialiased`}
      >
            <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
